server:
  port: 9001
#  servlet:
#    context-path: /xgwj
#    session:
#      timeout: 30m #30分钟

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mvc:
    servlet:
      load-on-startup: 1
    static-path-pattern: /static/** # js ,css 等静态文件路径

#  redis:
#    host: localhost
#    port: 6379

  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username:
    password:
    protocol: smtp
    test-connection: false

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
#    mode: LEGACYHTML5 # 去除htm5严格校验
    encoding: UTF-8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
